        - variable: addPrefix
          label: Add Prefix
          schema:
            type: list
            default: []
            items:
              - variable: addPrefixEntry
                label: ""
                schema:
                  additional_attrs: true
                  type: dict
                  attrs:
                    - variable: name
                      label: Name
                      schema:
                        type: string
                        required: true
                        default: ""
                    - variable: prefix
                      label: Prefix
                      schema:
                        type: string
                        required: true
                        default: ""
