        - variable: buffering
          label: Buffering
          schema:
            type: list
            default: []
            items:
              - variable: bufferingEntry
                label: ""
                schema:
                  additional_attrs: true
                  type: dict
                  attrs:
                    - variable: name
                      label: Name
                      schema:
                        type: string
                        required: true
                    - variable: maxRequestBodyBytes
                      label: Max Request Body Bytes
                      description: Leave empty and it won't be set
                      schema:
                        type: string
                        valid_chars: '^[0-9]*$'
                        default: ""
                    - variable: memRequestBodyBytes
                      label: Mem Request Body Bytes
                      description: Leave empty and it won't be set
                      schema:
                        type: string
                        valid_chars: '^[0-9]*$'
                        default: ""
                    - variable: maxResponseBodyBytes
                      label: Max Response Body Bytes
                      description: Leave empty and it won't be set
                      schema:
                        type: string
                        valid_chars: '^[0-9]*$'
                        default: ""
                    - variable: memResponseBodyBytes
                      label: Mem Response Body Bytes
                      description: Leave empty and it won't be set
                      schema:
                        type: string
                        valid_chars: '^[0-9]*$'
                        default: ""
                    - variable: retryExpression
                      label: Retry Expression
                      description: Leave empty and it won't be set
                      schema:
                        type: string
                        default: ""
