        - variable: chain
          label: Chain
          schema:
            type: list
            default: []
            items:
              - variable: chainEntry
                label: ""
                schema:
                  additional_attrs: true
                  type: dict
                  attrs:
                    - variable: name
                      label: Name
                      schema:
                        type: string
                        required: true
                    - variable: middlewares
                      label: Middlewares to Chain
                      schema:
                        type: list
                        default: []
                        items:
                          - variable: name
                            label: Name
                            schema:
                              type: string
                              required: true
                              default: ""
