        - variable: customFrameOptionsValue
          label: Custom Frame Options Value
          schema:
            type: list
            default: []
            items:
              - variable: customFrameOptionsValueEntry
                label: ""
                schema:
                  additional_attrs: true
                  type: dict
                  attrs:
                    - variable: name
                      label: Name
                      schema:
                        type: string
                        required: true
                    - variable: value
                      label: X-Frame-Options Header Value
                      description: The value of the header.
                      schema:
                        type: string
                        required: true
                        default: ""
