        - variable: forwardAuth
          label: forwardAuth
          schema:
            type: list
            default: []
            items:
              - variable: basicAuthEntry
                label: ""
                schema:
                  additional_attrs: true
                  type: dict
                  attrs:
                    - variable: name
                      label: Name
                      schema:
                        type: string
                        required: true
                        default: ""
                    - variable: address
                      label: Address
                      schema:
                        type: string
                        required: true
                        default: ""
                    - variable: trustForwardHeader
                      label: trustForwardHeader
                      schema:
                        type: boolean
                        default: false
                    - variable: tls
                      label: TLS
                      schema:
                        additional_attrs: true
                        type: dict
                        attrs:
                          - variable: insecureSkipVerify
                            label: insecureSkipVerify (expert)
                            description: >-
                              This disables all TLS certificate validation on communications with the authentication endpoint.
                              This could be a security risk and should only be used if you know what you are doing.
                            schema:
                              type: boolean
                              default: false
                    - variable: authResponseHeadersRegex
                      label: authResponseHeadersRegex
                      schema:
                        type: string
                        default: ""
                    - variable: authResponseHeaders
                      label: authResponseHeaders
                      schema:
                        type: list
                        default: []
                        items:
                          - variable: authResponseHeadersEntry
                            label: ""
                            schema:
                              type: string
                              default: ""
                    - variable: authRequestHeaders
                      label: authRequestHeaders
                      schema:
                        type: list
                        default: []
                        items:
                          - variable: authRequestHeadersEntry
                            label: ""
                            schema:
                              type: string
                              default: ""
