                          - variable: forwardedHeaders
                            label: Accept Forwarded Headers
                            schema:
                              additional_attrs: true
                              type: dict
                              attrs:
                                - variable: enabled
                                  label: Enable
                                  schema:
                                    type: boolean
                                    default: false
                                    show_subquestions_if: true
                                    subquestions:
                                      - variable: trustedIPs
                                        label: Trusted IPs
                                        description: Trust Forwarded Headers from specific IPs.
                                        schema:
                                          type: list
                                          default: []
                                          items:
                                            - variable: trustedIPsEntry
                                              label: ""
                                              schema:
                                                type: string
                                                required: true
                                                default: ""
                                      - variable: insecureMode
                                        label: Insecure Mode
                                        description: Always Trust Forwarded Headers
                                        schema:
                                          type: boolean
                                          default: false
