        - variable: ipWhiteList
          label: ipWhiteList
          schema:
            type: list
            default: []
            items:
              - variable: ipWhiteListEntry
                label: ""
                schema:
                  additional_attrs: true
                  type: dict
                  attrs:
                    - variable: name
                      label: Name
                      schema:
                        type: string
                        required: true
                        default: ""
                    - variable: sourceRange
                      label: Source Range
                      schema:
                        type: list
                        default: []
                        items:
                          - variable: sourceRangeEntry
                            label: ""
                            schema:
                              type: string
                              required: true
                              default: ""
                    - variable: ipStrategy
                      label: IP Strategy
                      schema:
                        additional_attrs: true
                        type: dict
                        attrs:
                          - variable: depth
                            label: Depth
                            schema:
                              type: int
                              required: true
                          - variable: excludedIPs
                            label: Excluded IPs
                            schema:
                              type: list
                              default: []
                              items:
                                - variable: excludedIPsEntry
                                  label: ""
                                  schema:
                                    type: string
                                    required: true
                                    default: ""
