        - variable: modsecurity
          label: modsecurity
          schema:
            type: list
            default: []
            items:
              - variable: modsecurityEntry
                label: ""
                schema:
                  additional_attrs: true
                  type: dict
                  attrs:
                    - variable: name
                      label: Name
                      description: This is a 3rd party plugin and not maintained by TrueCharts,
                        for more information go to <a href="https://github.com/acouvreur/traefik-modsecurity-plugin">traefik-modsecurity-plugin</a>
                      schema:
                        type: string
                        required: true
                        default: ""
                    - variable: modSecurityUrl
                      label: ModSecurity Url
                      description: It's the URL for the owasp/modsecurity container.
                      schema:
                        type: string
                        required: true
                        default: "https://someurl"
                    - variable: timeoutMillis
                      label: timeout Millis
                      description: timeout in milliseconds for the http client to talk with modsecurity container. (
                      schema:
                        type: int
                        required: true
                        default: 2
                    - variable: maxBodySize
                      label: maxBody Size
                      description: it's the maximum limit for requests body size. Requests exceeding this value will be rejected using HTTP 413 Request Entity Too Large. Zero means "use default value".
                      schema:
                        type: int
                        required: true
                        default: 0
