                          - variable: proxyProtocol
                            label: Accept Proxy Protocol connections
                            description: If Proxy Protocol header parsing is enabled for the entry point, this entry point can accept connections with or without Proxy Protocol headers.
                            schema:
                              additional_attrs: true
                              type: dict
                              attrs:
                                - variable: enabled
                                  label: Enable
                                  schema:
                                    type: boolean
                                    default: false
                                    show_subquestions_if: true
                                    subquestions:
                                      - variable: trustedIPs
                                        label: Trusted IPs
                                        description: Only IPs in trustedIPs will lead to remote client address replacement
                                        schema:
                                          type: list
                                          default: []
                                          items:
                                            - variable: trustedIPsEntry
                                              label: ""
                                              schema:
                                                type: string
                                                required: true
                                                default: ""
                                      - variable: insecureMode
                                        label: Insecure Mode
                                        description: Trust every incoming connection
                                        schema:
                                          type: boolean
                                          default: false
