        - variable: rateLimit
          label: rateLimit
          schema:
            type: list
            default: []
            items:
              - variable: rateLimitEntry
                label: ""
                schema:
                  additional_attrs: true
                  type: dict
                  attrs:
                    - variable: name
                      label: Name
                      schema:
                        type: string
                        required: true
                    - variable: average
                      label: Average
                      schema:
                        type: int
                        required: true
                        default: 300
                    - variable: burst
                      label: Burst
                      schema:
                        type: int
                        required: true
                        default: 200
