        - variable: realIP
          label: Real IP
          schema:
            type: list
            default: []
            items:
              - variable: realIPEntry
                label: ""
                schema:
                  additional_attrs: true
                  type: dict
                  attrs:
                    - variable: name
                      label: Name
                      schema:
                        type: string
                        required: true
                        default: ""
                    - variable: excludedNetworks
                      label: Excluded Networks
                      schema:
                        type: list
                        default: []
                        items:
                          - variable: excludedNetEntry
                            label: Excluded Network Entry
                            description: Network to exclude setting it to X-Real-Ip
                            schema:
                              type: string
                              required: true
                              default: ""
