        - variable: redirectScheme
          label: redirectScheme
          schema:
            type: list
            default: []
            items:
              - variable: redirectSchemeEntry
                label: ""
                schema:
                  additional_attrs: true
                  type: dict
                  attrs:
                    - variable: name
                      label: Name
                      schema:
                        type: string
                        required: true
                    - variable: scheme
                      label: Scheme
                      schema:
                        type: string
                        required: true
                        default: https
                        enum:
                          - value: https
                            description: https
                          - value: http
                            description: http
                    - variable: permanent
                      label: Permanent
                      schema:
                        type: boolean
                        default: false
