        - variable: stripPrefixRegex
          label: stripPrefixRegex
          schema:
            type: list
            default: []
            items:
              - variable: stripPrefixRegexEntry
                label: ""
                schema:
                  additional_attrs: true
                  type: dict
                  attrs:
                    - variable: name
                      label: Name
                      schema:
                        type: string
                        required: true
                    - variable: regex
                      label: Regex
                      schema:
                        type: list
                        default: []
                        items:
                          - variable: regexEntry
                            label: Regex
                            schema:
                              type: string
                              required: true
                              default: ""
