        - variable: themePark
          label: theme.park
          schema:
            type: list
            default: []
            items:
              - variable: themeParkEntry
                label: ""
                schema:
                  additional_attrs: true
                  type: dict
                  attrs:
                    - variable: name
                      label: Name
                      description: This is a 3rd party plugin and not maintained by TrueCharts,
                        for more information go to <a href="https://github.com/packruler/traefik-themepark">traefik-themepark</a>
                      schema:
                        type: string
                        required: true
                        default: ""
                    - variable: appName
                      label: App Name
                      description: Lower case, name of the app to be themed.
                        <br />Go to <a href="https://docs.theme-park.dev/themes/">https://docs.theme-park.dev/themes/</a> to see supported apps.
                      schema:
                        type: string
                        required: true
                        default: ""
                    - variable: themeName
                      label: Theme Name
                      description: Lower case, name of the theme to be applied.
                        <br />Go to <a href="https://docs.theme-park.dev/theme-options/">https://docs.theme-park.dev/theme-options/</a> to see supported themes.
                      schema:
                        type: string
                        required: true
                        default: ""
                    - variable: baseUrl
                      label: Base URL
                      description: Replace `https://theme-park.dev` URL for self-hosting reference.
                      schema:
                        type: string
                        required: true
                        default: https://theme-park.dev
                    - variable: addons
                      label: Addons
                      schema:
                        type: list
                        default: []
                        items:
                          - variable: addonEntry
                            label: Addon
                            description: Currently only supports 'darker' and '4k-logo' for *arr apps.
                              <br />Go to <a href="https://docs.theme-park.dev/themes/addons/">https://docs.theme-park.dev/themes/addons/</a> for Addon information.
                              <br />Go to <a href="https://github.com/packruler/traefik-themepark">https://github.com/packruler/traefik-themepark</a> for more context on plugin
                            schema:
                              type: string
                              required: true
                              default: ""
