apiVersion: v2
appVersion: "1.33.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.0.1
description: Gammu-smsd + apache2 + php5.6 + mysql + kalkun + systemd + some others 
keywords:
  - gammu
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: gammu-smsd
sources:
  - https://github.com/tomaszrim/gammu-smsd
  - https://hub.docker.com/r/distahl/gammu-smsd
version: 8.0.2
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
