                    - variable: middlewares
                      label: Traefik Middlewares
                      description: Add previously created Traefik Middlewares to this Ingress
                      schema:
                        type: list
                        default: []
                        items:
                          - variable: name
                            label: Name
                            schema:
                              type: string
                              default: ""
                              required: true
